version: "3.7"

services:
  iot_mqtt_client:
    container_name: iot_controller
    image: iot_controller:v1
    tty: true
    build:
      context: ../controller
      dockerfile: ../docker/controller/Dockerfile
    env_file:
      - ../platform_env/controller.env
      - ../platform_env/influxdb.env
    depends_on:
      - iot_influxdb
      - iot_mqtt_broker
    networks:
      - iot_cloud
    restart: always
  iot_influxdb:
    container_name: iot_influxdb
    image: influxdb:latest
    restart: always
    env_file:
      - ../platform_env/influxdb.env
    networks:
      - iot_cloud
    expose:
      - 8086
    ports:
      - "8086:8086"
    volumes:
      - iot_influxdb_volume:/var/lib/influxdb
      - ../configs/influxdb/influxdb.conf:/etc/influxdb/influxdb.conf
  iot_mqtt_broker:
    container_name: iot_mqtt_broker
    image: emqx/emqx:latest
    ports:
      - "18083:18083"
      - "3881:1883"
    expose:
      - 1883
    networks:
      - iot_cloud
    volumes:
      - ../configs/emqx/emqx.conf:/etc/emqx.conf
    restart: always
  iot_postgres_db:
    container_name: iot_postgres_db
    image: postgres:11
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - ../platform_env/postgres.env
    volumes:
      - iot_postgres_volume:/var/lib/postgresql/data
  iot_redis:
    container_name: iot_redis
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    networks:
      - iot_cloud
    volumes:
      - iot_redis_volume:/data
      - ../configs/redis/redis.conf:/usr/local/etc/redis/redis.conf
    expose:
      - 6379
  iot_nginx:
    container_name: iot_nginx
    image: nginx:latest
    restart: always
    ports:
      - "8080:80"
    networks:
      - iot_cloud
    # volumes:
     #  - ../configs/etc/nginx/conf.d/web_api.conf:/etc/nginx/conf.d/web_api.conf
    expose:
      - 8080
    command: [nginx-debug, '-g', 'daemon off;']
  iot_web_api:
    container_name: iot_web_api
    image: iot_web_api:v1
    tty: true
    build:
      context: ../web_api
      dockerfile: ../docker/web_api/Dockerfile
    env_file:
      - ../platform_env/influxdb.env
      - ../platform_env/postgres.env
      - ../platform_env/app.env
    env_file:
      - ../.env
    depends_on:
      - iot_nginx
      - iot_redis
      - iot_postgres_db
    networks:
      - iot_cloud

      
networks:
  iot_cloud:

volumes:
  iot_influxdb_volume:
  iot_postgres_volume:
  iot_redis_volume:
