version: "3.7"

services:
  iot_controller:
    container_name: iot_controller
    image: iot_controller:v1
    tty: true
    build:
      context: ../controller
      dockerfile: ../docker/controller/Dockerfile
    env_file:
      - ../.env
    depends_on:
      - iot_influxdb
      - iot_mqtt_broker
    networks:
      - iot_cloud
  iot_influxdb:
    container_name: iot_influxdb
    image: influxdb:latest
    restart: always
    env_file:
      - ../.env
    networks:
      - iot_cloud
    expose:
      - 8086
      - 8083
    ports:
      - "8086:8086"
      - "8083:8083"
    volumes:
      - iot_influxdb_volume:/var/lib/influxdb
      - ../configs/influxdb/influxdb.conf:/etc/influxdb/influxdb.conf
  iot_mqtt_broker:
    container_name: iot_mqtt_broker
    image: emqx/emqx:latest
    ports:
      - "18083:18083"
      - "3881:1883"
    expose:
      - 1883
    networks:
      - iot_cloud
    restart: always
  iot_postgres_db:
    container_name: iot_postgres_db
    image: postgres:11
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - ../platform_env/postgres.env
    volumes:
      - iot_postgres_volume:/var/lib/postgresql/data
      

networks:
  iot_cloud:

volumes:
  iot_influxdb_volume:
  iot_postgres_volume:
